version: "3.7"
services:
    inventory-planner:
      build: .
      links:
        - inventory-planner-db
      depends_on:
        - inventory-planner-db
      ports:
        - "5000:5000"
      networks:
        net:
          aliases:
            - inventory-planner.home
      container_name: inventory-planner
      hostname: inventory-planner
    inventory-planner-db:
      image: mysql:5.6
      command: mysqld --user=root --verbose
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: "inventory-planner"
        MYSQL_ROOT_PASSWORD: "password"
      healthcheck:
        test: mysqladmin -uroot -ppassword ping
        interval: 2s
        timeout: 5s
        retries: 30
      networks:
        net:
          aliases:
            - inventory-planner-db.home
      container_name: inventory-planner-db
      hostname: inventory-planner-db
    inventory-planner-db-seeder:
      build: inventory_planner_db_seeder/
      links:
        - inventory-planner-db
      depends_on:
        - inventory-planner-db
      networks:
        net:
          aliases:
            - inventory-planner-db-seeder.home
      container_name: inventory-planner-db-seeder
      hostname: inventory-planner-db-seeder
networks:
  net: