version: "2.1"
services:
    inventory-planner:
      build: .
      links:
        - inventory-planner-db
      ports:
        - "5000:8081"
    inventory-planner-db:
      image: mysql:5.6
      command: mysqld --user=root --verbose
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: "inventory-planner"
        MYSQL_ROOT_PASSWORD: "password"
      healthcheck:
        test: mysqladmin -uroot -ppassword ping
        interval: 2s
        timeout: 5s
        retries: 30
